# Generated by Django 4.2.11 on 2024-04-01 20:05

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_number', models.CharField(max_length=12)),
                ('date', models.DateField(default=datetime.date.today)),
                ('time_slot', models.CharField(choices=[('7AM', '7:00 - 8:30'), ('9AM', '9:00 - 10:30'), ('11AM', '11:00 - 12:30'), ('1PM', '13:00 - 14:30'), ('3PM', '15:00 - 16:30'), ('5PM', '17:00 - 18:30')], default='7AM', max_length=100)),
                ('choose_a_services', models.CharField(choices=[('Waste Collection', 'Waste Collection'), ('Site-to-Site Transfer', 'Site-to-Site Transfer'), ('Van and Driver Hire', 'Van and Driver Hire'), ('Additional Services - Write the details in Comments section', 'Additional Services - Write the details in Comments section')], default='Additional Services - Write the details in Comments section', max_length=100)),
                ('comments', models.TextField(max_length=250)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
