# Generated by Django 4.2.11 on 2024-04-14 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allbookings', '0002_alter_bookingrequest_time_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingrequest',
            name='choose_a_services',
            field=models.CharField(choices=[('Waste Collection', 'Waste Collection'), ('Site-to-Site Transfer', 'Site-to-Site Transfer'), ('Van and Driver Hire', 'Van and Driver Hire'), ('Additional Services - Write the details in Comments section', 'Additional Services - Write the details in Comments section')], max_length=100),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('cancelled', 'Cancelled')], max_length=20),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='time_slot',
            field=models.CharField(choices=[('7:00 - 8:30', '7:00 - 8:30'), ('9:00 - 10:30', '9:00 - 10:30'), ('11:00 - 12:30', '11:00 - 12:30'), ('13:00 - 14:30', '13:00 - 14:30'), ('15:00 - 16:30', '15:00 - 16:30'), ('17:00 - 18:30', '17:00 - 18:30')], max_length=100),
        ),
    ]
