# Generated by Django 4.2.11 on 2024-04-14 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allbookings', '0003_alter_bookingrequest_choose_a_services_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingrequest',
            name='date',
            field=models.DateField(),
        ),
    ]
