# Generated by Django 4.2.11 on 2024-03-23 18:24

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_homepage_featured_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='featured_image',
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('home_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.homepage')),
            ],
        ),
    ]
