# Generated by Django 4.2.11 on 2024-03-28 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('contact_number', models.CharField(max_length=20)),
                ('days_of_week', models.CharField(max_length=100)),
                ('time_slot', models.CharField(max_length=100)),
                ('services', models.CharField(max_length=100)),
                ('comments', models.TextField()),
            ],
        ),
    ]
